version: '3.5'
services:

  rabbit-1:
    image: rabbitmq:3.8-management
    hostname: rabbit-1
    container_name: rabbit-1
    volumes:
      - ${PWD}/config/rabbit-1/:/config/
    ports:
      - "8081:15672"
      - "8091:5672"
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE=coooookie

  rabbit-2:
    image: rabbitmq:3.8-management
    hostname: rabbit-2
    container_name: rabbit-2
    volumes:
      - ${PWD}/config/rabbit-2/:/config/
    ports:
      - "8082:15672"
      - "8092:5672"
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE=coooookie


  rabbit-3:
    image: rabbitmq:3.8-management
    hostname: rabbit-3
    container_name: rabbit-3
    volumes:
      - ${PWD}/config/rabbit-3/:/config/
    ports:
      - "8083:15672"
      - "8093:5672"
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE=coooookie
